'use client';

import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Manrope,
  Bebas_Neue,
  Anton_SC,
  Overpass,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-nueue",
  subsets: ["latin"],
  weight: "400",
});

const antonSc = Anton_SC({
  variable: "--font-anton-sc",
  subsets: ["latin"],
  weight: "400",
});

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${bebasNeue.variable} ${antonSc.variable} ${overpass.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
